// <auto-generated />
using System;
using DaftAlerts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaftAlerts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421230213_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DaftAlerts.Domain.Entities.FilterPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BerMin")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxBeds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int?>("MinBaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinBeds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyTypes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PropertyTypesJson");

                    b.Property<string>("RoutingKeys")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RoutingKeysJson");

                    b.HasKey("Id");

                    b.ToTable("FilterPresets", (string)null);
                });

            modelBuilder.Entity("DaftAlerts.Domain.Entities.GeocodeCache", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("GeocodeCache", (string)null);
                });

            modelBuilder.Entity("DaftAlerts.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Baths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Beds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BerRating")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("DaftId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DaftUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Eircode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MainImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawEmailMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecycledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutingKey")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DaftId")
                        .IsUnique();

                    b.HasIndex("ReceivedAt")
                        .IsDescending();

                    b.HasIndex("RoutingKey");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "ReceivedAt")
                        .IsDescending(false, true);

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("DaftAlerts.Domain.Entities.RawEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RawMimeBytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ParseStatus");

                    b.HasIndex("ReceivedAt");

                    b.ToTable("RawEmails", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
